% tools/generate_traceability_report.m
% Reads req_map.csv, verifies each cited block exists in missile.slx,
% and writes traceability_report.csv (machine-readable) plus
% traceability_report.html (rendered). Mirrors the autopilot / radar
% pattern so all three MBD repos ship the same artefact set.
%
% Columns:
%   ReqID       - REQ-MSL-***
%   Block       - block path in the model
%   Description - text from req_map.csv
%   Exists      - 1 if block resolves in the current model, else 0
%   HasProbe    - 1 if the row targets a real block or model file, else 0
%
% Called from tools/run_model_tests_and_build.m as part of CI.

function generate_traceability_report()
    repo_root = fileparts(fileparts(mfilename('fullpath')));
    csv_in  = fullfile(repo_root, 'req_map.csv');
    csv_out = fullfile(repo_root, 'traceability_report.csv');
    html_out = fullfile(repo_root, 'traceability_report.html');

    if ~exist(csv_in, 'file')
        error('generate_traceability_report:no_req_map', ...
            'req_map.csv not found at %s', csv_in);
    end

    fprintf('[trace] Reading %s\n', csv_in);
    T = readtable(csv_in, 'Delimiter', ',', 'TextType', 'string');
    if ~all(ismember({'ReqID','Block','Description'}, T.Properties.VariableNames))
        error('generate_traceability_report:bad_schema', ...
            'req_map.csv must have columns ReqID, Block, Description');
    end

    model = 'missile';
    was_loaded = bdIsLoaded(model);
    if ~was_loaded
        load_system(model);
    end

    fprintf('[trace] Checking block existence for %d requirements ...\n', height(T));
    exists = zeros(height(T), 1);
    hasProbe = zeros(height(T), 1);
    for k = 1:height(T)
        block_path = char(T.Block(k));

        % model/... entries point to parameter files, treat as always present
        if startsWith(block_path, 'model/')
            file_path = fullfile(repo_root, block_path);
            exists(k) = double(exist(file_path, 'file') == 2);
            hasProbe(k) = exists(k);
            continue
        end

        try
            h = getSimulinkBlockHandle(block_path);
            exists(k) = double(h ~= -1);
        catch
            exists(k) = 0;
        end
        hasProbe(k) = exists(k);
    end

    if ~was_loaded
        close_system(model, 0);
    end

    T.Exists = exists;
    T.HasProbe = hasProbe;

    fprintf('[trace] Writing %s\n', csv_out);
    writetable(T, csv_out);

    fprintf('[trace] Rendering %s\n', html_out);
    writeHtml(html_out, T);

    total = height(T);
    green = sum(exists);
    fprintf('[trace] Coverage: %d / %d requirements have resolvable blocks\n', green, total);
    if green < total
        warning('generate_traceability_report:orphans', ...
            '%d requirement(s) do not resolve in the current model', total - green);
    end
end

function writeHtml(path, T)
    fid = fopen(path, 'w');
    if fid < 0
        error('generate_traceability_report:cannot_write', ...
            'Cannot write %s', path);
    end
    c = onCleanup(@() fclose(fid));

    fprintf(fid, '<!doctype html>\n<html><head><meta charset="utf-8">\n');
    fprintf(fid, '<title>missile-mbd traceability</title>\n');
    fprintf(fid, '<style>\n');
    fprintf(fid, ' body { font-family: -apple-system, Segoe UI, Arial, sans-serif; margin: 24px; color: #222; }\n');
    fprintf(fid, ' h1 { font-size: 22px; margin-bottom: 4px; }\n');
    fprintf(fid, ' .meta { color: #666; font-size: 13px; margin-bottom: 20px; }\n');
    fprintf(fid, ' table { border-collapse: collapse; width: 100%%; font-size: 13px; }\n');
    fprintf(fid, ' th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; vertical-align: top; }\n');
    fprintf(fid, ' th { background: #f4f4f4; font-weight: 600; }\n');
    fprintf(fid, ' tr:nth-child(even) td { background: #fafafa; }\n');
    fprintf(fid, ' .ok { color: #2a7a2a; font-weight: 600; }\n');
    fprintf(fid, ' .bad { color: #a02020; font-weight: 600; }\n');
    fprintf(fid, ' code { background: #f0f0f0; padding: 1px 4px; border-radius: 3px; font-size: 12px; }\n');
    fprintf(fid, '</style></head><body>\n');

    fprintf(fid, '<h1>missile-mbd requirements traceability</h1>\n');
    fprintf(fid, '<div class="meta">');
    fprintf(fid, 'Generated by <code>tools/generate_traceability_report.m</code>. ');
    fprintf(fid, 'Total requirements: %d. Resolved in model: %d. ', height(T), sum(T.Exists));
    fprintf(fid, '</div>\n');

    fprintf(fid, '<table>\n<tr><th>ReqID</th><th>Block</th><th>Description</th><th>Exists</th><th>HasProbe</th></tr>\n');
    for k = 1:height(T)
        cls_e = 'ok';
        if T.Exists(k) ~= 1, cls_e = 'bad'; end
        cls_p = 'ok';
        if T.HasProbe(k) ~= 1, cls_p = 'bad'; end
        fprintf(fid, '<tr><td><code>%s</code></td><td><code>%s</code></td><td>%s</td>', ...
            htmlEscape(char(T.ReqID(k))), ...
            htmlEscape(char(T.Block(k))), ...
            htmlEscape(char(T.Description(k))));
        fprintf(fid, '<td class="%s">%d</td><td class="%s">%d</td></tr>\n', ...
            cls_e, T.Exists(k), cls_p, T.HasProbe(k));
    end
    fprintf(fid, '</table>\n</body></html>\n');
end

function s = htmlEscape(s)
    s = strrep(s, '&', '&amp;');
    s = strrep(s, '<', '&lt;');
    s = strrep(s, '>', '&gt;');
end
